#!/bin/bash
_tt() 
{
    local cur prev tt_completer
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    tt_completer="_tt_completer"
    if [[ ${cur} == ?* ]] ; then
        case "${prev}" in
            begin)
                local stopped_task_ids="`${tt_completer} task_ids pending stopped`"
                COMPREPLY=( $(compgen -W "${stopped_task_ids}" -- ${cur}) )
                return 0
                ;;
            stop)
                local started_task_ids="`${tt_completer} task_ids started`"
                COMPREPLY=( $(compgen -W "${started_task_ids}" -- ${cur}) )
                return 0
                ;;
            done)
                local stopped_task_ids="`${tt_completer} task_ids started stopped`"
                COMPREPLY=( $(compgen -W "${stopped_task_ids}" -- ${cur}) )
                return 0
                ;;
            *)
            ;;
        esac
    fi

    if [[ ${cur} == ?* ]] ; then
        local actions="`${tt_completer} actions`"
        COMPREPLY=( $(compgen -W "${actions}" -- ${cur}) )
    fi
}
complete -F _tt tt

